version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    volumes:
    - ./testdata/jobs:/var/jenkins_home/jobs
    ports:
    - 8080:8080
    networks:
    - jenkins
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false -Djenkins.install.SetupWizard.adminInitialApiToken=api_token -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true
      JENKINS_HOME: /var/jenkins_home
  jenkins-job-resource-ubuntu:
    build:
      context: .
      dockerfile: dockerfiles/test/ubuntu/Dockerfile
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_JOB: jenkins-job-resource-test
      JENKINS_JOB_TOKEN: job_token
      JENKINS_USERNAME: admin
      JENKINS_API_TOKEN: api_token
      JENKINS_JOB_ARTIFACT: output.txt
      JENKINS_JOB_RESULT: SUCCESS
    networks:
    - jenkins
    depends_on:
    - jenkins
  jenkins-job-resource-alpine:
    build:
      context: .
      dockerfile: dockerfiles/test/alpine/Dockerfile
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_JOB: jenkins-job-resource-test
      JENKINS_JOB_TOKEN: job_token
      JENKINS_USERNAME: admin
      JENKINS_API_TOKEN: api_token
      JENKINS_JOB_ARTIFACT: output.txt
      JENKINS_JOB_RESULT: SUCCESS
    networks:
    - jenkins
    depends_on:
    - jenkins

networks:
  jenkins:
