resource_types:
  - name: discord-resource
    type: registry-image
    source:
      repository: trivigy/discord-resource

  - name: jenkins-job-resource
    type: registry-image
    source:
      repository: logsquaredn/jenkins-job-resource
      tag: latest



resources:
  - name: jenkins-job-resource
    type: git
    icon: github
    check_every: 30m
    source:
      uri: https://github.com/logsquaredn/jenkins-job-resource/
      branch: master

  - name: jenkins-job-resource-image-alpine
    type: docker-image
    icon: docker
    check_every: 1h
    source: 
      username: ((docker.username))
      password: ((docker.password))
      repository: ((docker.username))/jenkins-job-resource
      tag: alpine

  - name: jenkins-job-resource-image-ubuntu
    type: docker-image
    icon: docker
    check_every: 1h
    source:
      username: ((docker.username))
      password: ((docker.password))
      repository: ((docker.username))/jenkins-job-resource

  - name: jenkins-job-resource-test
    type: jenkins-job-resource
    icon: test-tube
    check_every: 1h
    source:
      url: ((jenkins.url))
      job: ((jenkins.job.name))
      username: ((jenkins.username))
      password: ((jenkins.password))
      token: ((jenkins.job.token))

  # - name: notify
  #   type: discord-resource
  #   icon: discord
  #   check_every: 9999h
  #   source:
  #     token: ((discord.token))



anchors:
  - &default_job_config
    build_log_retention:
      builds: 12
      minimum_succeeded_builds: 3
    serial: true



groups:
  - name: build
    jobs: [update-pipeline, build-jenkins-job-resource-image-alpine, build-jenkins-job-resource-image-ubuntu]

  - name: test
    jobs: [test-job]


jobs:
  - name: update-pipeline
    <<: *default_job_config
    plan:
      - get: jenkins-job-resource
        trigger: true

      # - set_pipeline: self
      #   file: jenkins-job-resource/cicd/pipelines/jenkins-job-resource.yml
      #   var_files: ((var_files))


  - name: build-jenkins-job-resource-image-alpine
    <<: *default_job_config
    plan:
      - get: jenkins-job-resource
        passed: [update-pipeline]
        trigger: true

      - put: jenkins-job-resource-image-alpine
        params:
          build: jenkins-job-resource/
          tag_as_latest: false
          cache: true
          dockerfile: jenkins-job-resource/dockerfiles/alpine/Dockerfile
          additional_tags: jenkins-job-resource/dockerfiles/alpine/tags
        get_params:
          skip_download: true


  - name: build-jenkins-job-resource-image-ubuntu
    <<: *default_job_config
    plan:
      - get: jenkins-job-resource
        passed: [update-pipeline]
        trigger: true

      - put: jenkins-job-resource-image-ubuntu
        params:
          build: jenkins-job-resource/
          tag_as_latest: true
          cache: true
          dockerfile: jenkins-job-resource/dockerfiles/ubuntu/Dockerfile
          additional_tags: jenkins-job-resource/dockerfiles/ubuntu/tags
        get_params:
          skip_download: true


  - name: test-job
    <<: *default_job_config
    plan:
      - get: jenkins-job-resource-test
