name: Release
on:
  push:
    tags:
      - 'v*'
permissions: 
  contents: read
  packages: write 
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: setup-buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: goreleaser/goreleaser-action@v3
        with:
          args: release --rm-dist
